/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-uXfSUdZuzfpMdV1dimbpdWWwWwTiw4NaRf9Ky3UxEJ-o7HGRnSyahBTjTW7VhZLpFoWO7us2trxdAsjFytGxBDGcGUvU5bMzUIyyp5JadNWW-1a8jsmzGeRi",
  "tt": "tt-1-fKExgA4XpD5YpEFPjQVssTlVDsrYTL0xmQ52kvtmOB8=",
  "version": "2020-11-20"
}

export default ebconfig;